# https://taskfile.dev/

version: '3'

vars:
  VERSION:
    sh: git describe --tags --always --dirty 2>/dev/null || echo "dev"
  BRANCH:
    sh: git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown"
  DATE:
    sh: date -u +%Y-%m-%dT%H:%M:%SZ
  LDFLAGS: -ldflags "-X main.Version={{.VERSION}} -X main.Branch={{.BRANCH}} -X main.BuildDate={{.DATE}}"

tasks:
  build:
    desc: "Build the app"
    cmds:
      - go build {{.LDFLAGS}} -o dist/mdns-discovery .
    sources:
      - ./*.go
      - ./**/*.go

  run:
    desc: "Run the app"
    cmds:
      - task: build
      - ./dist/mdns-discovery {{ .CLI_ARGS }}
    watch: false
    interactive: true
  
  run:fake:
    desc: "Run the app with fake data"
    cmds:
      - task: run
        vars: { CLI_ARGS: '--fake {{ .CLI_ARGS }}'}

  debug:
    desc: "Watch debug log file"
    cmd: tail -f debug.log

  fmt:
    desc: "Run Formatting"
    cmd: go fmt ./...

  vhs:
    desc: "Run VHS demo gif generation"
    cmds:
      - cp dist/mdns-discovery .
      - vhs assets/demo.tape
      - rm ./mdns-discovery