# https://taskfile.dev/

version: '3'

tasks:
  build:
    desc: "Build the app"
    cmds:
      - go build -o dist/mdns-discovery .
    sources:
      - ./*.go
      - ./**/*.go

  run:
    desc: "Run the app"
    cmds:
      - task: build
      - ./dist/mdns-discovery {{ .CLI_ARGS }}
    watch: false
    interactive: true
  
  run:fake:
    desc: "Run the app with fake data"
    cmds:
      - task: run
        vars: { CLI_ARGS: '--fake {{ .CLI_ARGS }}'}

  debug:
    desc: "Watch debug log file"
    cmd: tail -f debug.log

  fmt:
    desc: "Run Formatting"
    cmd: go fmt ./...